### ISSUE TITLE
🎨自定义主题颜色（持续更新中）

### ISSUE THREAD

**Issue by FuShaoLei** [FuShaoLei/hexo-theme-hiya#1]
### 预览
![QQ截图20200430002004](https://user-images.githubusercontent.com/33645012/80853948-06b0ed80-8c67-11ea-8e05-f26605a1c5ac.png)
### 配置
```yml
color:
  bg: "#3E69AD"
  bg_dark: "#355993"
  bg_light: "#4779c7"
  normal_text: "#F0F2E5"
  highlight: "#F26339"
```
### 预览
![hiya](https://user-images.githubusercontent.com/33645012/80854001-64453a00-8c67-11ea-8a68-f5b2e1045207.png)
### 配置
```yml
color:
  bg: "#026A39"
  bg_dark: "#025a30"
  bg_light: "#027a42"
  normal_text: "#F0F2E5"
  highlight: "#F7BD08"
```

### 预览
![QQ截图20200430094647](https://user-images.githubusercontent.com/33645012/80854030-9060bb00-8c67-11ea-9888-4fbf6e3dcc83.png)
### 配置
```yml
color:
  bg: "#DE2910"
  bg_dark: "#bd230e"
  bg_light: "#ff2f12"
  normal_text: "#F0F2E5"
  highlight: "#FFDE00"
```
### 预览
![QQ截图20200430095340](https://user-images.githubusercontent.com/33645012/80854052-b4240100-8c67-11ea-94ca-5feee7f99e31.png)
### 配置
```yml
color:
  bg: "#5B0B90"
  bg_dark: "#4d097a"
  bg_light: "#690da6"
  normal_text: "#F0F2E5"
  highlight: "#EECA20"
```
### 预览
![QQ截图20200430095911](https://user-images.githubusercontent.com/33645012/80854077-d0c03900-8c67-11ea-86fd-0b74127d5dd5.png)
### 配置
```yml
color:
  bg: "#C1C2C5"
  bg_dark: "#a4a5a7"
  bg_light: "#dedfe3"
  normal_text: "#292E4B"
  highlight: "#B54047"
```

**Comment by FuShaoLei** [comment]
## 昼
### 预览
![QQ截图20200502114006](https://user-images.githubusercontent.com/33645012/80854324-c69f3a00-8c69-11ea-9223-b0a5d14313dc.png)
### 配置
```yml
color:
  bg: "#EEEEEE"
  bg_dark: "#cacaca"
  bg_light: "#ffffff"
  normal_text: "#000000"
  highlight: "#E51212"
```
## 夜
### 预览
![QQ截图20200430131324](https://user-images.githubusercontent.com/33645012/80854339-fea67d00-8c69-11ea-9e30-490838b7d0e3.png)

### 配置
```yml
color:
  bg: "#2E343B"
  bg_dark: "#272c32"
  bg_light: "#353c44"
  normal_text: "#F9FBFC"
  highlight: "#A22323"

```

**Comment by FuShaoLei** [comment]
## 贝吉塔
### 预览
![QQ截图20200502203743](https://user-images.githubusercontent.com/33645012/80864398-ea3ba200-8cb4-11ea-830c-d646d7fd2e9b.png)

### 配置
```yml
color:
  bg: "#1653A6"
  bg_dark: "#13478d"
  bg_light: "#195fbf"
  normal_text: "#F0F0F0"
  highlight: "#E3C36F"
```
